version: '3.5'
 
services:
  dd-agent-dogfood-jmx1:
    container_name: dd-agent-dogfood-jmx1
    image: gcr.io/datadoghq/agent:latest-jmx
    environment:
      - DD_HOSTNAME=datadog
      - DD_API_KEY
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true 
      - DD_PROCESS_AGENT_ENABLED=true 
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC="true" 
      - DD_LOG_LEVEL=debug
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE_LOGS="name:datadog-agent"
      - SD_JMX_ENABLE=true
    ports:
     - "8125:8125"
     - "8126:8126"
    volumes:
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app
   

  springasync:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.springasync
    container_name: springasync
    image: 'pejese/springasync:v0'
    environment:
            - JAVA_TOOL_OPTIONS=-javaagent:/root/dd-java-agent.jar -Ddd.agent.host=dd-agent-dogfood-jmx1 -Ddd.service=springasync -Ddd.env=dev -Ddd.version=12 -Ddd.tags=env:dev -Ddd.trace.http.client.split-by-domain=true -Ddd.profiling.enabled=true -XX:FlightRecorderOptions=stackdepth=256 -Ddd.profiling.ddprof.cpu.enabled=true -Ddd.trace.otel.enabled=true -Diteration=500000
    hostname: springasync
    ports:
          - "8080:8080"
    volumes:
      - $PWD/dd-java-agent.jar:/root/dd-java-agent.jar
    networks:
      - app


networks:
  app:
    external: false
    driver: bridge
    name: app
