version: '3.5'
 
services:
  dd-agent-dogfood-jmx1:
    container_name: dd-agent-dogfood-jmx1
    image: gcr.io/datadoghq/agent:latest-jmx
    environment:
      - DD_HOSTNAME=datadog
      - DD_API_KEY
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true 
      - DD_PROCESS_AGENT_ENABLED=true 
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true 
      - DD_LOG_LEVEL=debug
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE_LOGS="name:datadog-agent"
      - SD_JMX_ENABLE=true
    ports:
     - "8125:8125"
     - "8126:8126"
    volumes:
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app

  springjmx:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.springjmx
    container_name: springjmx
    image: 'pejese/springjmx:v0'
    labels:
      -  "com.datadoghq.ad.check_names = ['jmx']"
      -  "com.datadoghq.ad.instances = [{'host': '%%host%%', 'port': 5000}, 'tags': [ 'env:dev' ]]"
      -  "com.datadoghq.ad.init_configs=[{'is_jmx': true, 'collect_default_metrics': true, 'conf': [{'include': {'bean': 'custom:name=CustomMBean', 'attribute': ['Attribute'] } } ] }]"
    environment:
            - JAVA_TOOL_OPTIONS=-Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=5000 -Dcom.sun.management.jmxremote.rmi.port=5000 -Dcom.sun.management.jmxremote.host=0.0.0.0 -Djava.rmi.server.hostname=0.0.0.0 -javaagent:/app/dd-java-agent.jar -Ddd.agent.host=dd-agent-dogfood-jmx1 -Ddd.jmxfetch.enabled=false -Ddd.service=springjmx -Ddd.env=dev -Ddd.version=12 -Ddd.tags=env:dev -Ddd.trace.http.client.split-by-domain=true -Ddd.profiling.enabled=true -XX:FlightRecorderOptions=stackdepth=256 -Ddd.profiling.ddprof.cpu.enabled=true -Ddd.trace.otel.enabled=true -Diteration=500000
    hostname: springjmx
    ports:
          - "8080:8080"
          - "5000:5000"
    volumes:
      - $PWD/dd-java-agent.jar:/app/dd-java-agent.jar
    networks:
      - app

networks:
  app:
    external: false
    driver: bridge
    name: app
